version: "3.8"
services:
  app:
    container_name: app
    build: ./
    ports:
      - "5000:3000"
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - .:/media-guru
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 5s

  db:
    container_name: db_postgres
    image: postgres
    env_file:
      - ./.env
    ports:
      - "5434:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: curl --fail http://localhost:5434 || exit 1
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 5s
